// <auto-generated />
using System;
using BlazorBook.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBook.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207061648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ActivityStream.Abstractions.ActivityDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("Visibility");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("BlazorBook.Web.Data.Configurations.UserPasswordEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HashBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("UserId");

                    b.ToTable("UserPasswords", (string)null);
                });

            modelBuilder.Entity("Chat.Abstractions.ConversationDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("TenantId", "UpdatedAt");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("Chat.Abstractions.MessageDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedByProfileIds")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Media")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SystemMessageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ReplyToMessageId")
                        .HasFilter("ReplyToMessageId IS NOT NULL");

                    b.HasIndex("TenantId", "ConversationId", "CreatedAt");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Content.Abstractions.CommentDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactionCounts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViewerReaction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentCommentId")
                        .HasFilter("ParentCommentId IS NOT NULL");

                    b.HasIndex("TenantId", "PostId", "CreatedAt");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Content.Abstractions.PostDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactionCounts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ViewerReaction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("Posts", (string)null);
                });

            modelBuilder.Entity("Content.Abstractions.ReactionDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TargetId", "TargetKind")
                        .IsUnique()
                        .HasDatabaseName("IX_Reactions_Unique");

                    b.ToTable("Reactions", (string)null);
                });

            modelBuilder.Entity("Identity.Abstractions.MembershipDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasMaxLength(64)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("Identity.Abstractions.ProfileDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("Identity.Abstractions.SessionDto", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Identity.Abstractions.UserDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Inbox.Abstractions.FollowRequestDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("IdempotencyKey IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("FollowRequests", (string)null);
                });

            modelBuilder.Entity("Inbox.Abstractions.InboxItemDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreadKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasFilter("DedupKey IS NOT NULL");

                    b.HasIndex("ThreadKey")
                        .HasFilter("ThreadKey IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("InboxItems", (string)null);
                });

            modelBuilder.Entity("Media.Abstractions.MediaDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AltText")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailBlobPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UploadExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasFilter("DeletedAt IS NOT NULL");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("RelationshipService.Abstractions.RelationshipEdgeDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "Kind", "Scope")
                        .HasDatabaseName("IX_Relationships_Unique");

                    b.ToTable("RelationshipEdges", (string)null);
                });

            modelBuilder.Entity("Search.Abstractions.SearchDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Boost")
                        .HasColumnType("REAL");

                    b.Property<string>("DateFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumericFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEntity")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Boost");

                    b.HasIndex("TenantId", "DocumentType", "IndexedAt");

                    b.ToTable("SearchDocuments", (string)null);
                });

            modelBuilder.Entity("ActivityStream.Abstractions.ActivityDto", b =>
                {
                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Actor", b1 =>
                        {
                            b1.Property<string>("ActivityDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ActivityDtoId");

                            b1.ToTable("Activities");

                            b1.ToJson("Actor");

                            b1.WithOwner()
                                .HasForeignKey("ActivityDtoId");
                        });

                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Owner", b1 =>
                        {
                            b1.Property<string>("ActivityDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ActivityDtoId");

                            b1.ToTable("Activities");

                            b1.ToJson("Owner");

                            b1.WithOwner()
                                .HasForeignKey("ActivityDtoId");
                        });

                    b.OwnsOne("ActivityStream.Abstractions.ActivitySourceDto", "Source", b1 =>
                        {
                            b1.Property<string>("ActivityDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CorrelationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("IdempotencyKey")
                                .HasColumnType("TEXT");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ActivityDtoId");

                            b1.ToTable("Activities");

                            b1.ToJson("Source");

                            b1.WithOwner()
                                .HasForeignKey("ActivityDtoId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Chat.Abstractions.MessageDto", b =>
                {
                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Sender", b1 =>
                        {
                            b1.Property<string>("MessageDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AvatarUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MessageDtoId");

                            b1.ToTable("Messages");

                            b1.ToJson("Sender");

                            b1.WithOwner()
                                .HasForeignKey("MessageDtoId");
                        });

                    b.Navigation("Sender")
                        .IsRequired();
                });

            modelBuilder.Entity("Content.Abstractions.CommentDto", b =>
                {
                    b.OwnsOne("Content.Abstractions.EntityRefDto", "Author", b1 =>
                        {
                            b1.Property<string>("CommentDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CommentDtoId");

                            b1.ToTable("Comments");

                            b1.ToJson("Author");

                            b1.WithOwner()
                                .HasForeignKey("CommentDtoId");
                        });

                    b.Navigation("Author")
                        .IsRequired();
                });

            modelBuilder.Entity("Content.Abstractions.PostDto", b =>
                {
                    b.OwnsOne("Content.Abstractions.EntityRefDto", "Author", b1 =>
                        {
                            b1.Property<string>("PostDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PostDtoId");

                            b1.ToTable("Posts");

                            b1.ToJson("Author");

                            b1.WithOwner()
                                .HasForeignKey("PostDtoId");
                        });

                    b.Navigation("Author")
                        .IsRequired();
                });

            modelBuilder.Entity("Content.Abstractions.ReactionDto", b =>
                {
                    b.OwnsOne("Content.Abstractions.EntityRefDto", "Actor", b1 =>
                        {
                            b1.Property<string>("ReactionDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ReactionDtoId");

                            b1.ToTable("Reactions");

                            b1.ToJson("Actor");

                            b1.WithOwner()
                                .HasForeignKey("ReactionDtoId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();
                });

            modelBuilder.Entity("Inbox.Abstractions.FollowRequestDto", b =>
                {
                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "DecidedBy", b1 =>
                        {
                            b1.Property<string>("FollowRequestDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("FollowRequestDtoId");

                            b1.ToTable("FollowRequests");

                            b1.ToJson("DecidedBy");

                            b1.WithOwner()
                                .HasForeignKey("FollowRequestDtoId");
                        });

                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Requester", b1 =>
                        {
                            b1.Property<string>("FollowRequestDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("FollowRequestDtoId");

                            b1.ToTable("FollowRequests");

                            b1.ToJson("Requester");

                            b1.WithOwner()
                                .HasForeignKey("FollowRequestDtoId");
                        });

                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Target", b1 =>
                        {
                            b1.Property<string>("FollowRequestDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("FollowRequestDtoId");

                            b1.ToTable("FollowRequests");

                            b1.ToJson("Target");

                            b1.WithOwner()
                                .HasForeignKey("FollowRequestDtoId");
                        });

                    b.Navigation("DecidedBy");

                    b.Navigation("Requester")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Inbox.Abstractions.InboxItemDto", b =>
                {
                    b.OwnsOne("Inbox.Abstractions.InboxEventRefDto", "Event", b1 =>
                        {
                            b1.Property<string>("InboxItemDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("OccurredAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeKey")
                                .HasColumnType("TEXT");

                            b1.HasKey("InboxItemDtoId");

                            b1.ToTable("InboxItems");

                            b1.ToJson("Event");

                            b1.WithOwner()
                                .HasForeignKey("InboxItemDtoId");
                        });

                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Recipient", b1 =>
                        {
                            b1.Property<string>("InboxItemDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("InboxItemDtoId");

                            b1.ToTable("InboxItems");

                            b1.ToJson("Recipient");

                            b1.WithOwner()
                                .HasForeignKey("InboxItemDtoId");
                        });

                    b.Navigation("Event")
                        .IsRequired();

                    b.Navigation("Recipient")
                        .IsRequired();
                });

            modelBuilder.Entity("Media.Abstractions.MediaDto", b =>
                {
                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "Owner", b1 =>
                        {
                            b1.Property<string>("MediaDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MediaDtoId");

                            b1.ToTable("Media");

                            b1.ToJson("Owner");

                            b1.WithOwner()
                                .HasForeignKey("MediaDtoId");
                        });

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("RelationshipService.Abstractions.RelationshipEdgeDto", b =>
                {
                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "From", b1 =>
                        {
                            b1.Property<string>("RelationshipEdgeDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("RelationshipEdgeDtoId");

                            b1.ToTable("RelationshipEdges");

                            b1.ToJson("From");

                            b1.WithOwner()
                                .HasForeignKey("RelationshipEdgeDtoId");
                        });

                    b.OwnsOne("ActivityStream.Abstractions.EntityRefDto", "To", b1 =>
                        {
                            b1.Property<string>("RelationshipEdgeDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Display")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("RelationshipEdgeDtoId");

                            b1.ToTable("RelationshipEdges");

                            b1.ToJson("To");

                            b1.WithOwner()
                                .HasForeignKey("RelationshipEdgeDtoId");
                        });

                    b.Navigation("From")
                        .IsRequired();

                    b.Navigation("To")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
