using Media.Abstractions;
using SocialKit.Components.Abstractions;
using ActivityStream.Abstractions;

namespace BlazorBook.Web.Services;

/// <summary>
/// Media upload service that stores files locally in wwwroot/uploads.
/// Uses the blob path generated by MediaService to match URL resolution.
/// </summary>
public class LocalMediaUploadService : IMediaUploadService
{
    private readonly IMediaService _mediaService;
    private readonly IWebHostEnvironment _environment;
    private readonly ICurrentUserService _currentUser;
    private const string TenantId = "blazorbook";

    public LocalMediaUploadService(
        IMediaService mediaService,
        IWebHostEnvironment environment,
        ICurrentUserService currentUser)
    {
        _mediaService = mediaService;
        _environment = environment;
        _currentUser = currentUser;
    }

    public async Task<UploadedMedia> UploadAsync(
        string fileName,
        string contentType,
        byte[] data,
        CancellationToken ct = default)
    {
        var owner = new EntityRefDto
        {
            Kind = "user",
            Type = "Profile",
            Id = _currentUser.ProfileId ?? "unknown",
            Display = _currentUser.DisplayName
        };

        // Create media record
        var uploadRequest = new RequestUploadRequest
        {
            TenantId = TenantId,
            Owner = owner,
            FileName = fileName,
            ContentType = contentType,
            SizeBytes = data.Length,
            Purpose = "post"
        };

        var urlResult = await _mediaService.RequestUploadUrlAsync(uploadRequest, ct);

        // Extract blob path from upload URL (format: /uploads/{blobPath})
        // blobPath format: {tenantId}/{year}/{month}/{mediaId}/{fileName}
        var blobPath = urlResult.UploadUrl.StartsWith("/uploads/")
            ? urlResult.UploadUrl.Substring("/uploads/".Length)
            : $"{urlResult.MediaId}/{fileName}";

        // Save file locally using the blob path structure
        var uploadsPath = Path.Combine(_environment.WebRootPath, "uploads");
        var fullPath = Path.Combine(uploadsPath, blobPath.Replace('/', Path.DirectorySeparatorChar));
        var directory = Path.GetDirectoryName(fullPath);
        
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllBytesAsync(fullPath, data, ct);

        // Confirm upload
        var media = await _mediaService.ConfirmUploadAsync(TenantId, urlResult.MediaId, null, ct);

        return new UploadedMedia
        {
            MediaId = media.Id!,
            Url = $"/uploads/{blobPath}",
            ThumbnailUrl = null
        };
    }
}
