using Media.Abstractions;
using SocialKit.Components.Abstractions;
using ActivityStream.Abstractions;
using Microsoft.Extensions.Logging;

namespace BlazorBook.Web.Services;

/// <summary>
/// Media upload service that stores files locally in wwwroot/uploads.
/// Uses the blob path generated by MediaService to match URL resolution.
/// Also uploads to the storage provider so ConfirmUploadAsync can verify the blob.
/// </summary>
public class LocalMediaUploadService : IMediaUploadService
{
    private readonly IMediaService _mediaService;
    private readonly IMediaStorageProvider _storageProvider;
    private readonly IWebHostEnvironment _environment;
    private readonly ICurrentUserService _currentUser;
    private readonly ILogger<LocalMediaUploadService> _logger;
    private const string TenantId = "blazorbook";

    public LocalMediaUploadService(
        IMediaService mediaService,
        IMediaStorageProvider storageProvider,
        IWebHostEnvironment environment,
        ICurrentUserService currentUser,
        ILogger<LocalMediaUploadService> logger)
    {
        _mediaService = mediaService;
        _storageProvider = storageProvider;
        _environment = environment;
        _currentUser = currentUser;
        _logger = logger;
    }

    public async Task<UploadedMedia> UploadAsync(
        string fileName,
        string contentType,
        byte[] data,
        CancellationToken ct = default)
    {
        var owner = new EntityRefDto
        {
            Kind = "user",
            Type = "Profile",
            Id = _currentUser.ProfileId ?? "unknown",
            Display = _currentUser.DisplayName
        };

        // Create media record
        var uploadRequest = new RequestUploadRequest
        {
            TenantId = TenantId,
            Owner = owner,
            FileName = fileName,
            ContentType = contentType,
            SizeBytes = data.Length,
            Purpose = "post"
        };

        var urlResult = await _mediaService.RequestUploadUrlAsync(uploadRequest, ct);

        // Use the BlobPath from the result (format: {tenantId}/{year}/{month}/{mediaId}/{fileName})
        var blobPath = urlResult.BlobPath;

        // Save file locally using the blob path structure
        var uploadsPath = Path.Combine(_environment.WebRootPath, "uploads");
        var fullPath = Path.Combine(uploadsPath, blobPath.Replace('/', Path.DirectorySeparatorChar));
        var directory = Path.GetDirectoryName(fullPath);
        
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        await File.WriteAllBytesAsync(fullPath, data, ct);
        _logger.LogInformation("📁 Saved file locally: {FullPath}", fullPath);

        // Upload to storage provider so ConfirmUploadAsync can verify the blob exists
        try
        {
            _logger.LogInformation("☁️ Uploading to storage provider: {BlobPath} ({Size} bytes)", blobPath, data.Length);
            await _storageProvider.UploadBytesAsync(blobPath, data, contentType, ct);
            _logger.LogInformation("✅ Successfully uploaded to storage provider: {BlobPath}", blobPath);
            
            // Verify the blob exists
            var exists = await _storageProvider.ExistsAsync(blobPath, ct);
            _logger.LogInformation("🔍 Blob exists check: {BlobPath} = {Exists}", blobPath, exists);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "❌ Failed to upload to storage provider: {BlobPath}", blobPath);
            throw;
        }

        // Confirm upload
        _logger.LogInformation("📝 Confirming upload: MediaId={MediaId}", urlResult.MediaId);
        var media = await _mediaService.ConfirmUploadAsync(TenantId, urlResult.MediaId, null, ct);
        _logger.LogInformation("✅ Upload confirmed: MediaId={MediaId}", media.Id);

        return new UploadedMedia
        {
            MediaId = media.Id!,
            Url = $"/uploads/{blobPath}",
            ThumbnailUrl = null
        };
    }
}
