using ActivityStream.Abstractions;

namespace RelationshipService.Abstractions;

/// <summary>
/// Represents a relationship edge between two entities.
/// </summary>
public sealed class RelationshipEdgeDto
{
    /// <summary>
    /// Unique identifier for the edge. Generated by service if not provided.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Required partition key / tenant identifier.
    /// </summary>
    public required string TenantId { get; set; }

    /// <summary>
    /// The owner of the preference (viewer/subscriber).
    /// </summary>
    public required EntityRefDto From { get; set; }

    /// <summary>
    /// The subject (user/object/service/etc) that this relationship targets.
    /// </summary>
    public required EntityRefDto To { get; set; }

    /// <summary>
    /// The type of relationship.
    /// </summary>
    public required RelationshipKind Kind { get; set; }

    /// <summary>
    /// Defines which part of an activity this relationship applies to.
    /// Defaults to Any.
    /// </summary>
    public RelationshipScope Scope { get; set; } = RelationshipScope.Any;

    /// <summary>
    /// Optional filter controlling what the relationship applies to.
    /// For Block, filter is typically null (block everything).
    /// For Deny/Allow, filter is often used.
    /// </summary>
    public RelationshipFilterDto? Filter { get; set; }

    /// <summary>
    /// Whether this edge is currently active.
    /// Inactive edges are ignored in CanSeeAsync evaluations.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// When the edge was created. Set by service if default.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;
}
