using ActivityStream.Abstractions;
using RelationshipService.Abstractions;

namespace Inbox.Abstractions;

/// <summary>
/// Represents a follow/subscribe request awaiting approval.
/// </summary>
public sealed class FollowRequestDto
{
    /// <summary>
    /// Unique identifier. Generated by service if not provided.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Required partition key.
    /// </summary>
    public required string TenantId { get; set; }

    /// <summary>
    /// Requester (typically a Profile, not necessarily a User).
    /// </summary>
    public required EntityRefDto Requester { get; set; }

    /// <summary>
    /// The entity to follow/subscribe (may be private).
    /// </summary>
    public required EntityRefDto Target { get; set; }

    /// <summary>
    /// The type of relationship being requested (Follow or Subscribe).
    /// </summary>
    public required RelationshipKind RequestedKind { get; set; }

    /// <summary>
    /// Scope for the resulting relationship edge.
    /// Default: ActorOnly (for Follow typically).
    /// </summary>
    public RelationshipScope Scope { get; set; } = RelationshipScope.ActorOnly;

    /// <summary>
    /// Optional filter for the relationship.
    /// </summary>
    public RelationshipFilterDto? Filter { get; set; }

    /// <summary>
    /// Current status of the request.
    /// </summary>
    public FollowRequestStatus Status { get; set; } = FollowRequestStatus.Pending;

    /// <summary>
    /// Entity that made the approval/denial decision.
    /// </summary>
    public EntityRefDto? DecidedBy { get; set; }

    /// <summary>
    /// When the decision was made.
    /// </summary>
    public DateTimeOffset? DecidedAt { get; set; }

    /// <summary>
    /// Optional reason for the decision.
    /// </summary>
    public string? DecisionReason { get; set; }

    /// <summary>
    /// When the request was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;

    /// <summary>
    /// Dedup key for repeated UI submissions.
    /// Unique per (tenant, requester, target, requestedKind, scope).
    /// </summary>
    public string? IdempotencyKey { get; set; }
}
