using ActivityStream.Abstractions;

namespace Inbox.Abstractions;

/// <summary>
/// Represents an item in an inbox (notification or request).
/// </summary>
public sealed class InboxItemDto
{
    /// <summary>
    /// Unique identifier. Generated by service if not provided.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Required partition key.
    /// </summary>
    public required string TenantId { get; set; }

    /// <summary>
    /// Inbox owner entity (typically a Profile).
    /// </summary>
    public required EntityRefDto Recipient { get; set; }

    /// <summary>
    /// Type of inbox item.
    /// </summary>
    public required InboxItemKind Kind { get; set; }

    /// <summary>
    /// Reference to the event that triggered this item.
    /// </summary>
    public required InboxEventRefDto Event { get; set; }

    /// <summary>
    /// Human-readable title.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Human-readable body/description.
    /// </summary>
    public string? Body { get; set; }

    /// <summary>
    /// Related entities for "open" actions (invoice, project, thread, actor, etc).
    /// </summary>
    public List<EntityRefDto> Targets { get; set; } = new();

    /// <summary>
    /// Additional structured context (optional).
    /// </summary>
    public Dictionary<string, object?>? Data { get; set; }

    /// <summary>
    /// Current status of the item.
    /// </summary>
    public InboxItemStatus Status { get; set; } = InboxItemStatus.Unread;

    /// <summary>
    /// Used for deduping repeated generation.
    /// Example: "activity:{activityId}:recipient:{recipientKey}"
    /// </summary>
    public string? DedupKey { get; set; }

    /// <summary>
    /// Used for grouping threads.
    /// Example: "target:Invoice:inv_332:type:comment"
    /// </summary>
    public string? ThreadKey { get; set; }

    /// <summary>
    /// Number of events grouped into this thread.
    /// </summary>
    public int ThreadCount { get; set; } = 1;

    /// <summary>
    /// When the item was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;

    /// <summary>
    /// When the item was last updated (e.g., thread count incremented).
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }
}
