namespace ActivityStream.Abstractions;

/// <summary>
/// Canonical activity envelope. All activity types share this structure.
/// </summary>
public class ActivityDto
{
    /// <summary>
    /// Activity id. Optional on publish; generated by service if missing.
    /// ULID recommended for time-ordering.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Required partition key. Required even if single-tenant today.
    /// </summary>
    public required string TenantId { get; set; }

    /// <summary>
    /// Required activity type key: status.posted | invoice.paid | build.completed | etc
    /// </summary>
    public required string TypeKey { get; set; }

    /// <summary>
    /// When the activity actually occurred.
    /// </summary>
    public required DateTimeOffset OccurredAt { get; set; }

    /// <summary>
    /// When stored in the activity stream. Service should set if default.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;

    /// <summary>
    /// Required. Who/what caused the activity.
    /// </summary>
    public required EntityRefDto Actor { get; set; }

    /// <summary>
    /// Optional owner grouping (e.g., tenant/project/user timeline owner).
    /// </summary>
    public EntityRefDto? Owner { get; set; }

    /// <summary>
    /// Related entities (used for timelines/indexing).
    /// </summary>
    public List<EntityRefDto> Targets { get; set; } = new();

    /// <summary>
    /// Visibility (default Internal).
    /// </summary>
    public ActivityVisibility Visibility { get; set; } = ActivityVisibility.Internal;

    /// <summary>
    /// Optional human summary (recommended).
    /// </summary>
    public string? Summary { get; set; }

    /// <summary>
    /// Required type-specific payload. Can be empty object.
    /// </summary>
    public required object Payload { get; set; }

    /// <summary>
    /// Optional producer metadata and idempotency.
    /// </summary>
    public ActivitySourceDto? Source { get; set; }

    /// <summary>
    /// Optional tags for filtering/search.
    /// </summary>
    public List<string> Tags { get; set; } = new();
}
