namespace Identity.Abstractions;

/// <summary>
/// Represents a user's membership in a profile within a tenant.
/// </summary>
public sealed class MembershipDto
{
    /// <summary>
    /// Unique identifier. Generated by the service if not provided.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Tenant identifier. Memberships are tenant-scoped.
    /// </summary>
    public required string TenantId { get; set; }

    /// <summary>
    /// User identifier.
    /// </summary>
    public required string UserId { get; set; }

    /// <summary>
    /// Profile identifier.
    /// </summary>
    public required string ProfileId { get; set; }

    /// <summary>
    /// Role of the user in this profile.
    /// </summary>
    public ProfileRole Role { get; set; } = ProfileRole.Member;

    /// <summary>
    /// Status of the membership.
    /// </summary>
    public MembershipStatus Status { get; set; } = MembershipStatus.Active;

    /// <summary>
    /// Timestamp when the membership was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;
}
