namespace Identity.Abstractions;

/// <summary>
/// Represents a profile (actor/persona) that users can act as.
/// Profiles are global entities; their handles are globally unique.
/// </summary>
public sealed class ProfileDto
{
    /// <summary>
    /// Unique identifier. Generated by the service if not provided.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// Globally unique handle (username-like identifier for the profile).
    /// </summary>
    public required string Handle { get; set; }

    /// <summary>
    /// Optional display name.
    /// </summary>
    public string? DisplayName { get; set; }

    /// <summary>
    /// Optional avatar URL.
    /// </summary>
    public string? AvatarUrl { get; set; }

    /// <summary>
    /// If true, following this profile requires approval.
    /// </summary>
    public bool IsPrivate { get; set; } = false;

    /// <summary>
    /// Timestamp when the profile was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;
}
