namespace Identity.Abstractions;

/// <summary>
/// Represents a user identity (login principal).
/// </summary>
public sealed class UserDto
{
    /// <summary>
    /// Unique identifier. Generated by the service if not provided.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// User's email address. Globally unique.
    /// </summary>
    public required string Email { get; set; }

    /// <summary>
    /// User's username. Globally unique.
    /// </summary>
    public required string Username { get; set; }

    /// <summary>
    /// Optional display name.
    /// </summary>
    public string? DisplayName { get; set; }

    /// <summary>
    /// Whether the user account is active.
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Timestamp when the user was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = default;
}
